baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'Wright writes'

[module]
  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = true
    path = "github.com/adityatelange/hugo-PaperMod"  # Theme

[params]
  ShowShareButtons = false
  ShowReadingTime = true
  ShowCodeCopyButtons = true

[markup]
  [markup.highlight]
    style = 'doom-one'